#!/usr/bin/env python3
"""
uni_original.py -- run the ORIGINAL packed BOLO3.EXE under Unicorn.

Instead of hand-reconstructing PKLITE's relocation format, let PKLITE's own stub
do the work: load the packed EXE the way DOS would (load segment + apply the MZ
relocations), run the PKLITE stub -> it decompresses AND applies relocations, then
jumps to the QB startup, which (now correctly relocated) self-moves, decompresses,
relocates, and `ljmp cs:[0]` to the real program entry. We hook INT 21h for the
stub's DOS calls and trace the control flow to capture the resolved entry and the
fully-processed memory image.
"""
import struct
import sys
from unicorn import *
from unicorn.x86_const import *

EXE = "original/BOLO3.EXE"
TOTAL = 0x110000
LOAD_SEG = 0x0100                # DOS-like low load segment for the program
PSP_SEG = LOAD_SEG - 0x10


def dump_snapshot(uc, entry):
    import json
    mem = bytes(uc.mem_read(0, TOTAL))
    open("work/snapshot.bin", "wb").write(mem)
    rnames = ("ax", "bx", "cx", "dx", "si", "di", "bp", "sp",
              "cs", "ds", "es", "ss", "ip", "eflags")
    rids = dict(ax=UC_X86_REG_AX, bx=UC_X86_REG_BX, cx=UC_X86_REG_CX, dx=UC_X86_REG_DX,
                si=UC_X86_REG_SI, di=UC_X86_REG_DI, bp=UC_X86_REG_BP, sp=UC_X86_REG_SP,
                cs=UC_X86_REG_CS, ds=UC_X86_REG_DS, es=UC_X86_REG_ES, ss=UC_X86_REG_SS,
                ip=UC_X86_REG_IP, eflags=UC_X86_REG_EFLAGS)
    regs = {n: uc.reg_read(rids[n]) for n in rnames}
    regs["load_seg"] = LOAD_SEG
    regs["entry_seg"], regs["entry_off"] = entry
    json.dump(regs, open("work/snapshot_regs.json", "w"), indent=2)
    with open("src/recomp/gen/snapshot_regs.h", "w") as f:
        f.write("/* generated by tools/uni_original.py -- post-startup CPU state */\n"
                "#ifndef SNAPSHOT_REGS_H\n#define SNAPSHOT_REGS_H\n")
        for n in ("ax", "bx", "cx", "dx", "si", "di", "bp", "sp",
                  "cs", "ds", "es", "ss", "ip"):
            f.write(f"#define SNAP_{n.upper()} 0x{regs[n]:04X}\n")
        f.write(f"#define SNAP_LOAD_BASE 0x{LOAD_SEG*16:X}\n")
        f.write(f"#define SNAP_ENTRY_SEG 0x{entry[0]:04X}\n")
        f.write(f"#define SNAP_ENTRY_OFF 0x{entry[1]:04X}\n#endif\n")
    print(f"\n=== SNAPSHOT written: work/snapshot.bin ({len(mem)} B) + regs.json + regs.h ===")
    print("  regs:", {k: hex(v) for k, v in regs.items()})


def main():
    raw = open(EXE, "rb").read()
    (e_magic, e_cblp, e_cp, e_crlc, e_cparhdr, e_minalloc, e_maxalloc,
     e_ss, e_sp, e_csum, e_ip, e_cs, e_lfarlc, e_ovno) = struct.unpack_from("<14H", raw, 0)
    hdr_bytes = e_cparhdr * 16
    img_size = (e_cp - 1) * 512 + (e_cblp or 512) - hdr_bytes
    load_module = raw[hdr_bytes:hdr_bytes + img_size]
    print(f"MZ: hdr={hdr_bytes:#x} module={len(load_module):#x} relocs={e_crlc} "
          f"CS:IP={e_cs:04x}:{e_ip:04x} SS:SP={e_ss:04x}:{e_sp:04x}")

    uc = Uc(UC_ARCH_X86, UC_MODE_16)
    uc.mem_map(0, TOTAL)
    uc.mem_write(LOAD_SEG * 16, load_module)
    # PSP
    uc.mem_write(PSP_SEG * 16, b"\xCD\x20")
    uc.mem_write(PSP_SEG * 16 + 2, struct.pack("<H", 0x9FFF))   # top of memory
    # apply MZ relocations (add LOAD_SEG to each listed word)
    for i in range(e_crlc):
        off, seg = struct.unpack_from("<HH", raw, e_lfarlc + i * 4)
        a = ((PSP_SEG + 0x10 + seg) << 4) + off    # relocations are module-relative
        v = (struct.unpack("<H", uc.mem_read(a, 2))[0] + LOAD_SEG) & 0xFFFF
        uc.mem_write(a, struct.pack("<H", v))

    cs0 = (LOAD_SEG + e_cs) & 0xFFFF
    ss0 = (LOAD_SEG + e_ss) & 0xFFFF
    for r, v in ((UC_X86_REG_CS, cs0), (UC_X86_REG_IP, e_ip),
                 (UC_X86_REG_SS, ss0), (UC_X86_REG_SP, e_sp),
                 (UC_X86_REG_DS, PSP_SEG), (UC_X86_REG_ES, PSP_SEG),
                 (UC_X86_REG_AX, 0), (UC_X86_REG_BX, 0)):
        uc.reg_write(r, v)

    st = {"n": 0, "last_cs": None, "trans": 0}
    import os as _osn
    NMAX = int(_osn.environ.get('UNI_NMAX','30000000'))
    QB_ENTRY = (LOAD_SEG + 0x2011)      # the QB startup segment (post-PKLITE)

    ENTER_TRACE = "--enter-trace" in sys.argv
    starts = set()
    if ENTER_TRACE:
        import re as _re
        for m in _re.finditer(r"0x([0-9A-Fa-f]+)UL", open("src/recomp/gen/recomp_dispatch.c").read()):
            starts.add(int(m.group(1), 16))

    import os as _os2
    HEAPT = set(int(x, 0) for x in _os2.environ.get("UNI_HEAPTRACE", "").split(",") if x)
    def hook_code(uc, address, size, _):
        st["n"] += 1
        if HEAPT and address in HEAPT and st.get("at_entry"):
            cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
            si = uc.reg_read(UC_X86_REG_SI); ds = uc.reg_read(UC_X86_REG_DS)
            cx = uc.reg_read(UC_X86_REG_CX)
            tbl = struct.unpack("<8H", uc.mem_read(ds*16+si, 16))
            print(f"  [HEAP] IP {address:#07x} cs:ip={cs:04x}:{ip:04x} ds={ds:04x} si={si:04x} "
                  f"cx={cx:04x} ds:[si..]={['%04x'%w for w in tbl]} prev={st.get('prev',0):#07x}")
        if HEAPT and st.get("at_entry"):
            # General call-target collector: if the previous instruction was a CALL
            # (any form), the current address is its target. Collect them all so the
            # recomp can force them as function starts (covers indirect calls through
            # DGROUP routine tables -- init/handler/heap registration -- whose targets
            # land mid-function and are otherwise unreachable).
            p = st.get("prev", 0)
            i = p
            while i < p + 4 and uc.mem_read(i, 1)[0] in (0x26,0x2E,0x36,0x3E,0x64,0x65,0x66,0x67,0xF2,0xF3):
                i += 1
            op = uc.mem_read(i, 1)[0]
            is_call = op in (0xE8, 0x9A)
            if op == 0xFF:
                reg = (uc.mem_read(i + 1, 1)[0] >> 3) & 7
                is_call = reg in (2, 3)
            if is_call:
                st.setdefault("calltgts", {})[address] = uc.reg_read(UC_X86_REG_CS)
        st["prev"] = address
        cs = uc.reg_read(UC_X86_REG_CS)
        if cs != st["last_cs"]:
            st["trans"] += 1
            ip = uc.reg_read(UC_X86_REG_IP)
            tag = ""
            if cs == QB_ENTRY:
                tag = "  <== QB startup reached!"
            if st["trans"] <= 80:
                print(f"[{st['n']:9}] CS {st['last_cs']} -> {cs:04x}:{ip:04x} "
                      f"(lin {address:#07x}){tag}")
            st["last_cs"] = cs
        # capture the QB final handoff: jmp far cs:[bx] = 2E FF 2F
        code = uc.mem_read(address, 3)
        if bytes(code) == b"\x2e\xff\x2f":
            bx = uc.reg_read(UC_X86_REG_BX)
            a = (cs << 4) + bx
            off = struct.unpack("<H", uc.mem_read(a, 2))[0]
            seg = struct.unpack("<H", uc.mem_read(a + 2, 2))[0]
            print(f"\n*** QB ljmp cs:[bx] at {cs:04x}: target {seg:04x}:{off:04x} "
                  f"linear {(seg<<4)+off:#07x}")
            st["qb_entry"] = (seg, off)
        # at the real entry: either snapshot+stop, or begin function-entry tracing
        if "qb_entry" in st and cs == st["qb_entry"][0] and not st.get("at_entry"):
            st["at_entry"] = True
            arena_init()                       # build the DOS MCB arena (faithful DOS)
            if HEAPT:
                # heap-trace mode: just run past the entry (no snapshot/no enter cap)
                print(f"  [entry] reached; running with HEAPTRACE {sorted(HEAPT)}")
                return
            if not ENTER_TRACE:
                dump_snapshot(uc, st["qb_entry"])
                st["stop"] = "snapshot at real entry"; uc.emu_stop(); return
            st["tracing"] = True; st["ecount"] = 0
            t0 = struct.unpack("<H", uc.mem_read(0x1B8A0, 2))[0]
            print(f"  [entry] mem[0x1B8A0] (table[0]) = {t0:#06x}")
        if st.get("tracing"):
            lin = (cs << 4) + uc.reg_read(UC_X86_REG_IP)
            if lin in starts:
                if st["ecount"] < 200:
                    R = UC_X86_REG_AX, UC_X86_REG_BX, UC_X86_REG_CX, UC_X86_REG_DX, \
                        UC_X86_REG_SI, UC_X86_REG_DI, UC_X86_REG_BP, UC_X86_REG_DS, UC_X86_REG_ES
                    v = [uc.reg_read(r) & 0xFFFF for r in R]
                    print("E %06X cs=%04X:%04X ax=%04X bx=%04X cx=%04X dx=%04X si=%04X di=%04X bp=%04X ds=%04X es=%04X"
                          % (lin, cs, uc.reg_read(UC_X86_REG_IP) & 0xFFFF, *v))
                else:
                    print(f"E {lin:06X}")
                st["ecount"] += 1
                if st["ecount"] >= 4000:
                    st["stop"] = "enter-trace done"; uc.emu_stop(); return
        if st.get("at_entry") and st["n"] % 4000000 == 0:
            cs = uc.reg_read(UC_X86_REG_CS); si = uc.reg_read(UC_X86_REG_SI)
            tbl = struct.unpack("<8H", uc.mem_read(0x1E49*16+0x44F0, 16))
            hd = struct.unpack("<H", uc.mem_read(0x1E49*16+0x4846, 2))[0]
            print(f"  [pc] n={st['n']//1000000}M cs:ip={cs:04x}:{uc.reg_read(UC_X86_REG_IP):04x} "
                  f"si={si:04x} head[4846]={hd:04x} inittbl={['%04x'%w for w in tbl]}")
        if st["n"] > NMAX:
            uc.emu_stop()

    def cf(set_):
        fl = uc.reg_read(UC_X86_REG_EFLAGS)
        uc.reg_write(UC_X86_REG_EFLAGS, (fl | 1) if set_ else (fl & ~1))

    # ── Faithful DOS layer (mirrors src/recomp/dos_compat.c) — applied only AFTER
    # the real entry, so PKLITE+QB startup still use the known-good stubs above.
    def rd8(s, o):  return uc.mem_read(s * 16 + o, 1)[0]
    def rd16(s, o): return struct.unpack("<H", uc.mem_read(s * 16 + o, 2))[0]
    def wr16(s, o, v): uc.mem_write(s * 16 + o, struct.pack("<H", v & 0xFFFF))
    def wr8(s, o, v):  uc.mem_write(s * 16 + o, bytes([v & 0xFF]))
    def setreg16(r, v): uc.reg_write(r, v & 0xFFFF)
    PSP = PSP_SEG; MEMTOP = 0x9FFF
    def mcb_set(mcb, ty, owner, size):
        wr8(mcb, 0, ty); wr16(mcb, 1, owner); wr16(mcb, 3, size)
    def arena_init():
        mcb = PSP - 1
        mcb_set(mcb, 0x5A, PSP, MEMTOP - PSP)     # single free-ish Z block
        wr16(0x0080, 0x0000, mcb)
        st["first_mcb"] = mcb
    def arena_alloc(paras):
        mcb = st["first_mcb"]
        while True:
            ty = rd8(mcb, 0); owner = rd16(mcb, 1); size = rd16(mcb, 3)
            if owner == 0 and size >= paras:
                if size > paras + 1:
                    nxt = (mcb + 1 + paras) & 0xFFFF
                    mcb_set(nxt, ty, 0, size - paras - 1); mcb_set(mcb, 0x4D, PSP, paras)
                else:
                    wr16(mcb, 1, PSP)
                return (mcb + 1) & 0xFFFF
            if ty == 0x5A:
                return 0
            mcb = (mcb + 1 + size) & 0xFFFF
    def arena_resize(seg, paras):
        mcb = (seg - 1) & 0xFFFF
        ty = rd8(mcb, 0); cur = rd16(mcb, 3)
        if ty not in (0x4D, 0x5A): return -1
        if paras < cur:
            rem = (seg + paras) & 0xFFFF
            mcb_set(rem, ty, 0, cur - paras - 1); mcb_set(mcb, 0x4D, rd16(mcb, 1), paras)
        else:
            wr16(mcb, 3, paras)
        return 0
    R = dict(AX=UC_X86_REG_AX, BX=UC_X86_REG_BX, CX=UC_X86_REG_CX, DX=UC_X86_REG_DX,
             ES=UC_X86_REG_ES, DS=UC_X86_REG_DS, SI=UC_X86_REG_SI, DI=UC_X86_REG_DI)
    def faithful21(ah):
        al = uc.reg_read(R['AX']) & 0xFF
        if ah == 0x30: setreg16(R['AX'], 0x0005); return True            # DOS 5.0
        if ah == 0x25:                                                   # set vector
            n = al; ds = uc.reg_read(R['DS']); dx = uc.reg_read(R['DX'])
            st.setdefault("ivt", {})[n] = (ds << 16) | dx; return True
        if ah == 0x35:                                                   # get vector
            v = st.get("ivt", {}).get(al, 0)
            setreg16(R['ES'], v >> 16); setreg16(R['BX'], v & 0xFFFF); return True
        if ah == 0x48:                                                   # allocate
            seg = arena_alloc(uc.reg_read(R['BX']))
            if seg: setreg16(R['AX'], seg); cf(False)
            else:   setreg16(R['AX'], 8); cf(True)
            return True
        if ah == 0x49:                                                   # free
            wr16((uc.reg_read(R['ES']) - 1) & 0xFFFF, 1, 0); cf(False); return True
        if ah == 0x4A:                                                   # resize
            if arena_resize(uc.reg_read(R['ES']), uc.reg_read(R['BX'])) == 0: cf(False)
            else: setreg16(R['AX'], 9); cf(True)
            return True
        if ah == 0x52:                                                   # list of lists
            setreg16(R['ES'], 0x0080); setreg16(R['BX'], 0x0002); return True
        if ah == 0x44:                                                   # IOCTL
            if al == 0: setreg16(R['DX'], 0x80D3)
            cf(False); return True
        if ah == 0x62:                                                   # get PSP
            setreg16(R['BX'], PSP); return True
        if ah in (0x06, 0x0B):                                           # console: no key
            if ah == 0x0B: setreg16(R['AX'], (uc.reg_read(R['AX']) & 0xFF00) | 0x00)
            elif (uc.reg_read(R['DX']) & 0xFF) == 0xFF:
                fl = uc.reg_read(UC_X86_REG_EFLAGS); uc.reg_write(UC_X86_REG_EFLAGS, fl | 0x40)
                setreg16(R['AX'], uc.reg_read(R['AX']) & 0xFF00)
            cf(False); return True
        return False

    handles = {}
    def hook_intr(uc, intno, _):
        ax = uc.reg_read(UC_X86_REG_AX); ah = (ax >> 8) & 0xFF
        if intno == 0x21:
            if ah == 0x4C:
                st["stop"] = f"INT21/4C exit {ax & 0xFF}"; uc.emu_stop(); return
            if st.get("at_entry") and faithful21(ah):     # faithful DOS post-entry
                return
            if ah == 0x30:
                uc.reg_write(UC_X86_REG_AX, 0x0005); return
            if ah in (0x4A, 0x48, 0x49, 0x25, 0x35, 0x1A):
                if ah == 0x48: uc.reg_write(UC_X86_REG_AX, 0x4000)
                cf(False); return
            if ah == 0x3D:                       # OPEN FILE -- the asset loader!
                dx = uc.reg_read(UC_X86_REG_DX); ds = uc.reg_read(UC_X86_REG_DS)
                a = (ds << 4) + dx
                name = bytes(uc.mem_read(a, 16)).split(b"\x00")[0].decode("latin1", "replace")
                st.setdefault("opens", []).append(name)
                print(f"  *** INT21/3D OPEN '{name}'  (game asset load reached!)")
                # try to satisfy it from disk so the game keeps going
                import os
                path = os.path.join("original", os.path.basename(name))
                if os.path.exists(path):
                    fd = len(handles) + 5; handles[fd] = open(path, "rb")
                    uc.reg_write(UC_X86_REG_AX, fd); cf(False)
                else:
                    uc.reg_write(UC_X86_REG_AX, 2); cf(True)   # file not found
                if len(st["opens"]) >= (999 if HEAPT else 3):
                    st["stop"] = "reached asset loading"; uc.emu_stop()
                return
            # Faithful INT 21h ONLY after the real entry (during PKLITE+QB startup we
            # must keep the known-good stub behavior that reaches the entry).
            if st.get("at_entry"):
                if ah == 0x44:                   # IOCTL — match dos_compat.c
                    if (ax & 0xFF) == 0:
                        uc.reg_write(UC_X86_REG_DX, 0x80D3)   # char device (CON)
                    cf(False); return
                if ah == 0x62:                   # get PSP -> BX (dos_compat: 0x00F0)
                    uc.reg_write(UC_X86_REG_BX, 0x00F0); cf(False); return
            cf(False); return                    # other INT 21h -> succeed-ish
        if intno == 0x20:
            st["stop"] = "INT 20h"; uc.emu_stop(); return
        # other INTs (10h video, 16h kbd, 1Ah timer): ignore/stub

    uc.hook_add(UC_HOOK_CODE, hook_code)
    uc.hook_add(UC_HOOK_INTR, hook_intr)

    import os as _os
    if _os.environ.get("UNI_EGA"):       # detect EGA framebuffer writes (drawing)
        def hook_ega(uc, access, address, size, value, _):
            if 0xA0000 <= address < 0xB0000 and st.get("at_entry"):
                st["ega"] = st.get("ega", 0) + 1
                if st["ega"] <= 3:
                    cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
                    print(f"  [EGA-W] {address:#07x} <= {value:#x} by {cs:04x}:{ip:04x} n={st['n']}")
        uc.hook_add(UC_HOOK_MEM_WRITE, hook_ega)

    WATCH = int(os.environ.get("UNI_WATCH", "0"), 0) if "os" in dir() else 0
    WATCH = int(_os.environ.get("UNI_WATCH", "0"), 0)
    if WATCH and st.get is not None:
        def hook_mw(uc, access, address, size, value, _):
            if WATCH <= address < WATCH + 2 and st.get("at_entry"):
                cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
                ds = uc.reg_read(UC_X86_REG_DS)
                print(f"  [W] {address:#07x} <= {value:#06x} ({size}B) by {cs:04x}:{ip:04x} ds={ds:04x} n={st['n']}")
        uc.hook_add(UC_HOOK_MEM_WRITE, hook_mw)

    begin = cs0 * 16 + e_ip
    print(f"start {cs0:04x}:{e_ip:04x} (lin {begin:#07x}); QB startup seg = {QB_ENTRY:#06x}")
    try:
        uc.emu_start(begin, TOTAL, count=NMAX)
    except UcError as e:
        cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
        print(f"\nUcError: {e} after {st['n']} insns at {cs:04x}:{ip:04x}")
        pc = (cs << 4) + ip
        print("  bytes@pc:", bytes(uc.mem_read(pc, 16)).hex(' '))
        return
    if st.get("calltgts"):
        ct = st["calltgts"]   # {linear_addr: cs}
        import json as _json
        open("work/calltgts.json", "w").write(_json.dumps({str(a): ct[a] for a in sorted(ct)}))
        print(f"\nCALL TARGETS ({len(ct)}) collected -> work/calltgts.json (addr:cs)")
    _fcs = uc.reg_read(UC_X86_REG_CS); _fip = uc.reg_read(UC_X86_REG_IP)
    print(f"\nstopped: {st.get('stop')} after {st['n']} insns, {st['trans']} CS transitions; "
          f"final cs:ip={_fcs:04x}:{_fip:04x} lin {(_fcs<<4)+_fip:#07x}")
    if "ega" in st:
        print(f"EGA framebuffer writes (A000): {st['ega']}")
    if "qb_entry" in st:
        print("QB REAL ENTRY:", st["qb_entry"])


if __name__ == "__main__":
    main()
