#!/usr/bin/env python3
"""
uni_original.py -- run the ORIGINAL packed BOLO3.EXE under Unicorn.

Instead of hand-reconstructing PKLITE's relocation format, let PKLITE's own stub
do the work: load the packed EXE the way DOS would (load segment + apply the MZ
relocations), run the PKLITE stub -> it decompresses AND applies relocations, then
jumps to the QB startup, which (now correctly relocated) self-moves, decompresses,
relocates, and `ljmp cs:[0]` to the real program entry. We hook INT 21h for the
stub's DOS calls and trace the control flow to capture the resolved entry and the
fully-processed memory image.
"""
import struct
import sys
from unicorn import *
from unicorn.x86_const import *

EXE = "original/BOLO3.EXE"
TOTAL = 0x110000
LOAD_SEG = 0x0100                # DOS-like low load segment for the program
PSP_SEG = LOAD_SEG - 0x10


def dump_snapshot(uc, entry):
    import json
    mem = bytes(uc.mem_read(0, TOTAL))
    open("work/snapshot.bin", "wb").write(mem)
    rnames = ("ax", "bx", "cx", "dx", "si", "di", "bp", "sp",
              "cs", "ds", "es", "ss", "ip", "eflags")
    rids = dict(ax=UC_X86_REG_AX, bx=UC_X86_REG_BX, cx=UC_X86_REG_CX, dx=UC_X86_REG_DX,
                si=UC_X86_REG_SI, di=UC_X86_REG_DI, bp=UC_X86_REG_BP, sp=UC_X86_REG_SP,
                cs=UC_X86_REG_CS, ds=UC_X86_REG_DS, es=UC_X86_REG_ES, ss=UC_X86_REG_SS,
                ip=UC_X86_REG_IP, eflags=UC_X86_REG_EFLAGS)
    regs = {n: uc.reg_read(rids[n]) for n in rnames}
    regs["load_seg"] = LOAD_SEG
    regs["entry_seg"], regs["entry_off"] = entry
    json.dump(regs, open("work/snapshot_regs.json", "w"), indent=2)
    with open("src/recomp/gen/snapshot_regs.h", "w") as f:
        f.write("/* generated by tools/uni_original.py -- post-startup CPU state */\n"
                "#ifndef SNAPSHOT_REGS_H\n#define SNAPSHOT_REGS_H\n")
        for n in ("ax", "bx", "cx", "dx", "si", "di", "bp", "sp",
                  "cs", "ds", "es", "ss", "ip"):
            f.write(f"#define SNAP_{n.upper()} 0x{regs[n]:04X}\n")
        f.write(f"#define SNAP_LOAD_BASE 0x{LOAD_SEG*16:X}\n")
        f.write(f"#define SNAP_ENTRY_SEG 0x{entry[0]:04X}\n")
        f.write(f"#define SNAP_ENTRY_OFF 0x{entry[1]:04X}\n#endif\n")
    print(f"\n=== SNAPSHOT written: work/snapshot.bin ({len(mem)} B) + regs.json + regs.h ===")
    print("  regs:", {k: hex(v) for k, v in regs.items()})


def main():
    raw = open(EXE, "rb").read()
    (e_magic, e_cblp, e_cp, e_crlc, e_cparhdr, e_minalloc, e_maxalloc,
     e_ss, e_sp, e_csum, e_ip, e_cs, e_lfarlc, e_ovno) = struct.unpack_from("<14H", raw, 0)
    hdr_bytes = e_cparhdr * 16
    img_size = (e_cp - 1) * 512 + (e_cblp or 512) - hdr_bytes
    load_module = raw[hdr_bytes:hdr_bytes + img_size]
    print(f"MZ: hdr={hdr_bytes:#x} module={len(load_module):#x} relocs={e_crlc} "
          f"CS:IP={e_cs:04x}:{e_ip:04x} SS:SP={e_ss:04x}:{e_sp:04x}")

    uc = Uc(UC_ARCH_X86, UC_MODE_16)
    uc.mem_map(0, TOTAL)
    uc.mem_write(LOAD_SEG * 16, load_module)
    # PSP
    uc.mem_write(PSP_SEG * 16, b"\xCD\x20")
    uc.mem_write(PSP_SEG * 16 + 2, struct.pack("<H", 0x9FFF))   # top of memory
    # apply MZ relocations (add LOAD_SEG to each listed word)
    for i in range(e_crlc):
        off, seg = struct.unpack_from("<HH", raw, e_lfarlc + i * 4)
        a = ((PSP_SEG + 0x10 + seg) << 4) + off    # relocations are module-relative
        v = (struct.unpack("<H", uc.mem_read(a, 2))[0] + LOAD_SEG) & 0xFFFF
        uc.mem_write(a, struct.pack("<H", v))

    cs0 = (LOAD_SEG + e_cs) & 0xFFFF
    ss0 = (LOAD_SEG + e_ss) & 0xFFFF
    for r, v in ((UC_X86_REG_CS, cs0), (UC_X86_REG_IP, e_ip),
                 (UC_X86_REG_SS, ss0), (UC_X86_REG_SP, e_sp),
                 (UC_X86_REG_DS, PSP_SEG), (UC_X86_REG_ES, PSP_SEG),
                 (UC_X86_REG_AX, 0), (UC_X86_REG_BX, 0)):
        uc.reg_write(r, v)

    st = {"n": 0, "last_cs": None, "trans": 0}
    NMAX = 30_000_000
    QB_ENTRY = (LOAD_SEG + 0x2011)      # the QB startup segment (post-PKLITE)

    ENTER_TRACE = "--enter-trace" in sys.argv
    starts = set()
    if ENTER_TRACE:
        import re as _re
        for m in _re.finditer(r"0x([0-9A-Fa-f]+)UL", open("src/recomp/gen/recomp_dispatch.c").read()):
            starts.add(int(m.group(1), 16))

    import os as _os2
    HEAPT = set(int(x, 0) for x in _os2.environ.get("UNI_HEAPTRACE", "").split(",") if x)
    def hook_code(uc, address, size, _):
        st["n"] += 1
        if HEAPT and address in HEAPT and st.get("at_entry"):
            cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
            si = uc.reg_read(UC_X86_REG_SI); ds = uc.reg_read(UC_X86_REG_DS)
            cx = uc.reg_read(UC_X86_REG_CX)
            tbl = struct.unpack("<8H", uc.mem_read(ds*16+si, 16))
            print(f"  [HEAP] IP {address:#07x} cs:ip={cs:04x}:{ip:04x} ds={ds:04x} si={si:04x} "
                  f"cx={cx:04x} ds:[si..]={['%04x'%w for w in tbl]} prev={st.get('prev',0):#07x}")
        if HEAPT and st.get("at_entry") and st.get("prev") == 0x146E5:
            # the instruction AFTER the init-dispatcher's `call word ds:[si]` is the
            # resolved init-routine entry -- collect them all (image offsets).
            st.setdefault("inittgts", set()).add(address)
        st["prev"] = address
        cs = uc.reg_read(UC_X86_REG_CS)
        if cs != st["last_cs"]:
            st["trans"] += 1
            ip = uc.reg_read(UC_X86_REG_IP)
            tag = ""
            if cs == QB_ENTRY:
                tag = "  <== QB startup reached!"
            if st["trans"] <= 80:
                print(f"[{st['n']:9}] CS {st['last_cs']} -> {cs:04x}:{ip:04x} "
                      f"(lin {address:#07x}){tag}")
            st["last_cs"] = cs
        # capture the QB final handoff: jmp far cs:[bx] = 2E FF 2F
        code = uc.mem_read(address, 3)
        if bytes(code) == b"\x2e\xff\x2f":
            bx = uc.reg_read(UC_X86_REG_BX)
            a = (cs << 4) + bx
            off = struct.unpack("<H", uc.mem_read(a, 2))[0]
            seg = struct.unpack("<H", uc.mem_read(a + 2, 2))[0]
            print(f"\n*** QB ljmp cs:[bx] at {cs:04x}: target {seg:04x}:{off:04x} "
                  f"linear {(seg<<4)+off:#07x}")
            st["qb_entry"] = (seg, off)
        # at the real entry: either snapshot+stop, or begin function-entry tracing
        if "qb_entry" in st and cs == st["qb_entry"][0] and not st.get("at_entry"):
            st["at_entry"] = True
            if HEAPT:
                # heap-trace mode: just run past the entry (no snapshot/no enter cap)
                print(f"  [entry] reached; running with HEAPTRACE {sorted(HEAPT)}")
                return
            if not ENTER_TRACE:
                dump_snapshot(uc, st["qb_entry"])
                st["stop"] = "snapshot at real entry"; uc.emu_stop(); return
            st["tracing"] = True; st["ecount"] = 0
            t0 = struct.unpack("<H", uc.mem_read(0x1B8A0, 2))[0]
            print(f"  [entry] mem[0x1B8A0] (table[0]) = {t0:#06x}")
        if st.get("tracing"):
            lin = (cs << 4) + uc.reg_read(UC_X86_REG_IP)
            if lin in starts:
                if st["ecount"] < 200:
                    R = UC_X86_REG_AX, UC_X86_REG_BX, UC_X86_REG_CX, UC_X86_REG_DX, \
                        UC_X86_REG_SI, UC_X86_REG_DI, UC_X86_REG_BP, UC_X86_REG_DS, UC_X86_REG_ES
                    v = [uc.reg_read(r) & 0xFFFF for r in R]
                    print("E %06X cs=%04X:%04X ax=%04X bx=%04X cx=%04X dx=%04X si=%04X di=%04X bp=%04X ds=%04X es=%04X"
                          % (lin, cs, uc.reg_read(UC_X86_REG_IP) & 0xFFFF, *v))
                else:
                    print(f"E {lin:06X}")
                st["ecount"] += 1
                if st["ecount"] >= 4000:
                    st["stop"] = "enter-trace done"; uc.emu_stop(); return
        if st["n"] > NMAX:
            uc.emu_stop()

    def cf(set_):
        fl = uc.reg_read(UC_X86_REG_EFLAGS)
        uc.reg_write(UC_X86_REG_EFLAGS, (fl | 1) if set_ else (fl & ~1))

    handles = {}
    def hook_intr(uc, intno, _):
        ax = uc.reg_read(UC_X86_REG_AX); ah = (ax >> 8) & 0xFF
        if intno == 0x21:
            if ah == 0x4C:
                st["stop"] = f"INT21/4C exit {ax & 0xFF}"; uc.emu_stop(); return
            if ah == 0x30:
                uc.reg_write(UC_X86_REG_AX, 0x0005); return
            if ah in (0x4A, 0x48, 0x49, 0x25, 0x35, 0x1A):
                if ah == 0x48: uc.reg_write(UC_X86_REG_AX, 0x4000)
                cf(False); return
            if ah == 0x3D:                       # OPEN FILE -- the asset loader!
                dx = uc.reg_read(UC_X86_REG_DX); ds = uc.reg_read(UC_X86_REG_DS)
                a = (ds << 4) + dx
                name = bytes(uc.mem_read(a, 16)).split(b"\x00")[0].decode("latin1", "replace")
                st.setdefault("opens", []).append(name)
                print(f"  *** INT21/3D OPEN '{name}'  (game asset load reached!)")
                # try to satisfy it from disk so the game keeps going
                import os
                path = os.path.join("original", os.path.basename(name))
                if os.path.exists(path):
                    fd = len(handles) + 5; handles[fd] = open(path, "rb")
                    uc.reg_write(UC_X86_REG_AX, fd); cf(False)
                else:
                    uc.reg_write(UC_X86_REG_AX, 2); cf(True)   # file not found
                if len(st["opens"]) >= (999 if HEAPT else 3):
                    st["stop"] = "reached asset loading"; uc.emu_stop()
                return
            cf(False); return                    # other INT 21h -> succeed-ish
        if intno == 0x20:
            st["stop"] = "INT 20h"; uc.emu_stop(); return
        # other INTs (10h video, 16h kbd, 1Ah timer): ignore/stub

    uc.hook_add(UC_HOOK_CODE, hook_code)
    uc.hook_add(UC_HOOK_INTR, hook_intr)

    WATCH = int(os.environ.get("UNI_WATCH", "0"), 0) if "os" in dir() else 0
    import os as _os
    WATCH = int(_os.environ.get("UNI_WATCH", "0"), 0)
    if WATCH and st.get is not None:
        def hook_mw(uc, access, address, size, value, _):
            if WATCH <= address < WATCH + 2 and st.get("at_entry"):
                cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
                ds = uc.reg_read(UC_X86_REG_DS)
                print(f"  [W] {address:#07x} <= {value:#06x} ({size}B) by {cs:04x}:{ip:04x} ds={ds:04x} n={st['n']}")
        uc.hook_add(UC_HOOK_MEM_WRITE, hook_mw)

    begin = cs0 * 16 + e_ip
    print(f"start {cs0:04x}:{e_ip:04x} (lin {begin:#07x}); QB startup seg = {QB_ENTRY:#06x}")
    try:
        uc.emu_start(begin, TOTAL, count=NMAX)
    except UcError as e:
        cs = uc.reg_read(UC_X86_REG_CS); ip = uc.reg_read(UC_X86_REG_IP)
        print(f"\nUcError: {e} after {st['n']} insns at {cs:04x}:{ip:04x}")
        pc = (cs << 4) + ip
        print("  bytes@pc:", bytes(uc.mem_read(pc, 16)).hex(' '))
        return
    if st.get("inittgts"):
        tg = sorted(st["inittgts"])
        print(f"\nINIT-ROUTINE TARGETS ({len(tg)}) via call word ds:[si] @0x146E5:")
        print(" ".join(f"0x{t:05X}" for t in tg))
    print(f"\nstopped: {st.get('stop')} after {st['n']} insns, {st['trans']} CS transitions")
    if "qb_entry" in st:
        print("QB REAL ENTRY:", st["qb_entry"])


if __name__ == "__main__":
    main()
